# -*- coding: utf-8 -*-
"""Rainfall.app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DcmFAbZR_KiA-dXkrHd6T4QJN5LYkc0q
"""

pip install streamlit

# %%

import streamlit as st
import joblib
import numpy as np
from PIL import Image

# %%
gnb = joblib.load('rainfall_model.pkl')

# %%
st.title('Rainfall Prediction Model')
st.header('Input Features')
pressure = st.number_input('Enter pressure')
dewpoint = st.number_input('Enter dewpoint')
humidity = st.number_input('Enter hunidity')
cloud = st.number_input('Enter cloud')
sunshine = st.number_input('Enter sunshine')
winddirection = st.number_input('Enter winddirection')
windspeed = st.number_input('Enter windspeed')

if st.button('predict'):
    input_length = np.array([pressure,dewpoint,humidity,cloud,sunshine,winddirection,windspeed]).reshape(1,-1)
    if gnb.predict(input_length)==1:
        st.subheader('It is Raining')
        img = Image.open('rain.jpg')
        st.image(img,caption='Rain',use_container_width=True)

    else:
        st.subheader('Not Raining')
        img = Image.open('norain.jpg')
        st.image(img,caption='Not Raining',use_container_width=True)

# %%